# Use an official Python runtime as a base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy the client code into the container
COPY ./Client/client.py /app

# Install dependencies
RUN pip install flask requests

# Expose the client server port
EXPOSE 5001

# Run the client app
CMD ["python", "client.py"]
