apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: api
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres-service/postgres
            - name: REDIS_HOST
              value: redis-service
          ports:
            - containerPort: 5000
